# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: peak_flow_utils 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "peak_flow_utils"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kaspernj"]
  s.date = "2016-10-08"
  s.description = "Various utilities to help with building on PeakFlow"
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/peak_flow_utils.rb",
    "lib/peak_flow_utils/rspec_helper.rb",
    "peak_flow_utils.gemspec",
    "spec/peak_flow_utils_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kaspernj/peak_flow_utils"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Various utilities to help with building on PeakFlow"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["= 1.12.5"])
      s.add_development_dependency(%q<jeweler>, ["= 2.1.1"])
      s.add_development_dependency(%q<best_practice_project>, ["= 0.0.8"])
      s.add_development_dependency(%q<rubocop>, ["= 0.43.0"])
    else
      s.add_dependency(%q<bundler>, ["= 1.12.5"])
      s.add_dependency(%q<jeweler>, ["= 2.1.1"])
      s.add_dependency(%q<best_practice_project>, ["= 0.0.8"])
      s.add_dependency(%q<rubocop>, ["= 0.43.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["= 1.12.5"])
    s.add_dependency(%q<jeweler>, ["= 2.1.1"])
    s.add_dependency(%q<best_practice_project>, ["= 0.0.8"])
    s.add_dependency(%q<rubocop>, ["= 0.43.0"])
  end
end

